# Generated by Django 5.0 on 2023-12-26 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
    ]
