# Generated by Django 5.0 on 2023-12-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0002_alter_client_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name_client",
        ),
        migrations.AddField(
            model_name="client",
            name="fname_client",
            field=models.CharField(
                db_column="Fname_client", default="NULL", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="lname_client",
            field=models.CharField(
                db_column="Lname_client", default="NULL", max_length=50
            ),
        ),
    ]
